(()=>{'use strict';
const P=window.P;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],PC={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}},K='kmate-v4';
const today=()=>{let d=new Date;return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')},fresh=()=>({s:[],m:[],a:0,f:0,x:0,b:0,d:{date:today(),s:[]},sound:true});
let S;try{S={...fresh(),...JSON.parse(localStorage.getItem(K)||'{}')}}catch{S=fresh()}S.s=Array.isArray(S.s)?S.s:[];S.m=Array.isArray(S.m)?S.m:[];if(!S.d||!Array.isArray(S.d.s)||S.d.date!==today())S.d={date:today(),s:[]};
let Q=[],qi=0,p=null,B=new Map,turn='w',ori='w',sel=null,last=null,hints=[],done=false,first=true,counted=false,revealed=false,timer,audio=null;
function save(){try{localStorage.setItem(K,JSON.stringify(S))}catch{}dash()}
function add(a,x){if(!a.includes(x))a.push(x)}function del(a,x){let i=a.indexOf(x);if(i>-1)a.splice(i,1)}
function showView(id){$$('.view').forEach(v=>v.hidden=v.id!==id);$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='progress')dash();try{scrollTo({top:0,behavior:'smooth'})catch{} }
function start(course='middlegame',mode='course',id){let a=mode==='review'?P.filter(x=>S.m.includes(x.i)):mode==='mixed'?P:P.filter(x=>x.c===course);if(!a.length){toast('No mistakes yet—starting mixed practice.');a=P}let u=a.filter(x=>!S.s.includes(x.i)),r=a.filter(x=>S.s.includes(x.i));Q=[...u,...r];if(id){let j=Q.findIndex(x=>x.i===id);if(j>0)Q.unshift(...Q.splice(j,1))}qi=0;load();showView('practice')}
function parse(f){B=new Map;let [pos,t]=f.split(/\s+/);turn=t==='b'?'b':'w';pos.split('/').forEach((r,ri)=>{let fi=0;for(let ch of r){if(/\d/.test(ch))fi+=+ch;else{B.set('abcdefgh'[fi]+(8-ri),{c:ch===ch.toUpperCase()?'w':'b',t:ch.toLowerCase()});fi++}}})}
function load(){p=Q[qi];if(!p){showView('progress');return}parse(p.f);ori=turn;sel=null;last=null;hints=[];done=false;first=true;counted=false;revealed=false;$('#coursepill').textContent=p.c==='middlegame'?'Middlegame':'Endgame';$('#title').textContent=p.n;$('#goal').textContent=p.g;$('#counter').textContent=(qi+1)+' of '+Q.length+' · '+p.t+' · '+'●'.repeat(p.d)+'○'.repeat(3-p.d);$('#side').textContent=turn==='w'?'White to move':'Black to move';$('#attempt').textContent='First attempt';$('#hintbox').hidden=true;$('#answerbox').hidden=true;$('#hint').hidden=false;$('#answer').hidden=false;$('#next').hidden=true;$('#hint').textContent='Hint';$('#hint').dataset.n=0;setMsg('Tap a piece, then its destination.','');let sc=p.c==='middlegame'?['Checks, captures, threats','King safety and loose pieces','Pawn breaks and worst-placed piece']:['King activity','Passed pawns and races','Opposition, checks and rook activity'];$('#scan').innerHTML=sc.map(x=>'<li>'+x+'</li>').join('');board()}
function squares(){let fs=ori==='w'?'abcdefgh':'hgfedcba',rs=ori==='w'?'87654321':'12345678';return [...rs].flatMap(r=>[...fs].map(f=>f+r))}
function board(){let e=$('#board');e.innerHTML='';squares().forEach((s,n)=>{let q=B.get(s),b=document.createElement('button');b.type='button';b.dataset.square=s;b.className='sq '+((('abcdefgh'.indexOf(s[0])+Number(s[1]))%2)?'light':'dark')+(s===sel?' selected':'')+(hints.includes(s)?' hinted':'')+(last&&(last.from===s||last.to===s)?' last':'');b.setAttribute('aria-label',s+(q?' '+q.c+q.t:' empty'));if(q){let z=document.createElement('span');z.className='piece';z.textContent=PC[q.c][q.t];b.append(z)}if(n%8===0){let z=document.createElement('span');z.className='coord rank';z.textContent=s[1];b.append(z)}if(n>=56){let z=document.createElement('span');z.className='coord file';z.textContent=s[0];b.append(z)}b.addEventListener('click',()=>tap(s));e.append(b)})}
function tap(s){if(done||!p)return;let q=B.get(s);if(!sel){if(q&&q.c===turn){sel=s;board()}return}if(q&&q.c===turn){sel=s;board();return}let base=sel+s,promo=p.a.find(x=>x.startsWith(base)&&x.length===5);if(promo){promote(base);return}judge(base)}
function promote(base){let box=$('#promos');box.innerHTML='';for(let t of ['q','r','b','n']){let b=document.createElement('button');b.type='button';b.textContent=PC[turn][t];b.addEventListener('click',()=>{closeDialog('promotion');judge(base+t)});box.append(b)}openDialog('promotion')}
function apply(m){let f=m.slice(0,2),t=m.slice(2,4),pr=m[4],q=B.get(f);if(!q)return;B.delete(f);B.set(t,{c:q.c,t:pr||q.t});if(q.t==='k'&&Math.abs('abcdefgh'.indexOf(f[0])-'abcdefgh'.indexOf(t[0]))===2){let rf=(t[0]==='g'?'h':'a')+t[1],rt=(t[0]==='g'?'f':'d')+t[1],r=B.get(rf);if(r){B.delete(rf);B.set(rt,r)}}}
function judge(m){if(p.a.includes(m)){apply(m);last={from:m.slice(0,2),to:m.slice(2,4)};sel=null;done=true;hints=[];if(!counted){S.a++;counted=true}add(S.s,p.i);add(S.d.s,p.i);if(first&&!revealed){S.f++;S.x++;S.b=Math.max(S.b,S.x);del(S.m,p.i)}else{S.x=0;add(S.m,p.i)}save();setMsg(nice(m)+' — correct.','good');explain(false);tone(660);board()}else{if(!counted){S.a++;counted=true}first=false;S.x=0;add(S.m,p.i);save();sel=null;$('#attempt').textContent='Try again';setMsg('That move misses the main idea. Look again.','bad');tone(180);board()}}
function nice(m){return m.slice(0,2)+'–'+m.slice(2,4)+(m[4]?'='+m[4].toUpperCase():'')}
function setMsg(x,t){$('#statusText').textContent=x;$('#status').className='status '+t}
function explain(shown){$('#answerbox').hidden=false;$('#result').textContent=shown?'Move shown':'Correct';$('#explain').textContent=p.e;$('#takeaway').textContent=p.k;$('#hint').hidden=true;$('#answer').hidden=true;$('#next').hidden=false}
function giveHint(){let n=Math.min((+$('#hint').dataset.n||0)+1,p.h.length);$('#hint').dataset.n=n;$('#hintbox').hidden=false;$('#hinttext').textContent=p.h[n-1];$('#hint').textContent=n<p.h.length?'Another hint':'Hint shown';if(n===p.h.length){let a=p.a[0];hints=[a.slice(0,2),a.slice(2,4)];board()}}
function reveal(){if(done)return;revealed=true;first=false;if(!counted){S.a++;counted=true}add(S.m,p.i);S.x=0;parse(p.f);let a=p.a[0];apply(a);last={from:a.slice(0,2),to:a.slice(2,4)};done=true;save();setMsg('Best move shown: '+nice(a)+'.','');explain(true);tone(360);board()}
function next(){qi++;if(qi>=Q.length){toast('Session complete. Nice work.');showView('progress');return}load()}
function dash(){let mid=P.filter(x=>x.c==='middlegame'&&S.s.includes(x.i)).length,end=P.filter(x=>x.c==='endgame'&&S.s.includes(x.i)).length,d=S.d.s.length;$('#topstat').textContent=S.s.length+' solved · '+S.x+' streak';$('#daily').textContent=d;$('#ring').style.setProperty('--pct',Math.min(100,d/5*100)+'%');$('#midcount').textContent=mid+'/10';$('#endcount').textContent=end+'/10';$('#midbar').style.width=mid*10+'%';$('#endbar').style.width=end*10+'%';$('#solvedStat').textContent=S.s.length;$('#accuracy').textContent=S.a?Math.round(S.f/S.a*100)+'%':'—';$('#streakStat').textContent=S.x;$('#reviewStat').textContent=S.m.length;$('#pmidlabel').textContent=mid+' of 10';$('#pendlabel').textContent=end+' of 10';$('#pmid').style.width=mid*10+'%';$('#pend').style.width=end*10+'%';let list=$('#recommendations');list.innerHTML='';let rec=[...P.filter(x=>S.m.includes(x.i)),...P.filter(x=>!S.s.includes(x.i)&&!S.m.includes(x.i))].slice(0,4);for(let x of rec){let b=document.createElement('button');b.className='rec';b.innerHTML='<span><b>'+x.n+'</b><small>'+(x.c==='middlegame'?'Middlegame':'Endgame')+' · '+x.t+'</small></span><strong>Train</strong>';b.addEventListener('click',()=>start(x.c,'course',x.i));list.append(b)}}
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>e.classList.remove('show'),2400)}
function tone(f){if(!S.sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.11)}catch{}}
function openDialog(id){let d=$('#'+id);if(d.showModal)d.showModal();else d.hidden=false}function closeDialog(id){let d=$('#'+id);if(d.close)d.close();else d.hidden=true}
function bind(){$$('[data-start]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.start)));$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>start('middlegame',b.dataset.mode)));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='practice'&&!p)start();else showView(b.dataset.view)}));$('#brand').addEventListener('click',()=>showView('home'));$('#back').addEventListener('click',()=>showView('home'));$('#flip').addEventListener('click',()=>{ori=ori==='w'?'b':'w';board()});$('#hint').addEventListener('click',giveHint);$('#answer').addEventListener('click',reveal);$('#next').addEventListener('click',next);$('#sound').addEventListener('click',()=>{S.sound=!S.sound;save();$('#sound').textContent=S.sound?'♪':'×'});$('#reset').addEventListener('click',()=>{if(confirm('Reset all K-Mate progress on this device?')){S=fresh();save();toast('Progress reset.')}});$('#install').addEventListener('click',()=>openDialog('installDialog'));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.dataset.close)))}
try{bind();dash();showView('home');document.documentElement.dataset.ready='1';window.__KMATE__={version:'4.0',start,get:()=>({p:p?.i||null,view:$$('.view').find(v=>!v.hidden)?.id,squares:B.size})}}catch(e){console.error(e);let t=$('#toast');t.textContent='K-Mate could not start. Reload once.';t.classList.add('show')}
})();